# Network Configuration
network: mainnet
network_config:
  rpc_endpoint: "https://api.mainnet-beta.solana.com"
  orca_api: "https://api.orca.so"
  max_retries: 3
  retry_delay: 1

# Trading Parameters
trading_params:
  candle_interval: 60  # 1 minute
  update_interval: 3
  cache_duration: 10
  min_liquidity: 10000
  min_volume_24h: 1000
  position_size: 0.1
  take_profit: 0.05
  stop_loss: 0.02

# Risk Management
risk_management:
  max_position_size: 1.0
  max_daily_loss: 5.0
  max_drawdown: 10.0
  max_open_positions: 3
  min_liquidity: 10000
  max_slippage: 0.01

# Backtest Settings
backtest:
  start_balance: 1000
  fee_rate: 0.003
  slippage_model: "fixed"
  fixed_slippage: 0.001

# Trading Settings
trading_enabled: true
backtesting_mode: false
max_trades_per_day: 100
min_profit_threshold: 0.005  # 0.5%

# Meme Strategy Settings
meme_strategy:
  min_momentum_score: 50
  entry_momentum_threshold: 70
  exit_momentum_threshold: 30
  min_liquidity_score: 60
  min_volume_score: 50
  base_position_size: 0.1
  max_position_size: 1.0
  stop_loss_percentage: 0.02
  take_profit_percentage: 0.05
  target_liquidity: 100000
  target_volume_24h: 50000

# Trading Parameter
max_slippage: 0.01
min_liquidity: 50000
trade_check_interval: 60

# Orca Pool Settings
orca_pool_min_size: 10000
orca_pool_address: ""  # Wird dynamisch gesetzt

# Monitoring
system_check_interval: 300